add three files in weather_status
necst-telescope/neclib pull request #192
Opened 2022-10-17 07:37 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #185 

まだわかっていない部分も多いのですが、ひとまず今できることをしてあります。

2022-10-20 00:34 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +        return data["temp" + 273.15] * u.K
dictの中身の取り出し方を確認してください。

2022-10-20 00:39 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +        return data["humid"]
u.Quantityになっていますか？

2022-10-20 00:54 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +from typing import Literal
使わないものは削除してください。

2022-10-20 17:15 UTC, takayama-27 commented on neclib/devices/weather_status/tr73u.py
> +        return data["humid"]
湿度は％なので単位がない、というようなことを聞き単位をつけていません。
単位なし、という単位をつけますか？

2022-10-21 04:24 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +        return data["humid"]
単位をつけずにfloatでreturnすること自体はOKです。ですが、そうするなら24行目のreturnの型ヒントをfloatにしてください。

2022-10-22 14:35 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +        return data["temp"] + 273.15 * u.K
単位の付け方に注意してください

2022-10-22 14:43 UTC, FumikaDemachi commented on neclib/devices/weather_status/weather_base.py
> +    def get_humid(self) -> u.Quantity:
ここも直してください

2022-10-23 23:34 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +        return data_K["temp"]
```suggestion
        data_K = data["temp"] * u.K + 273.15 * u.K
        return data_K
```

2022-10-24 03:11 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +from numpy import float64
numpy のfloat64ではなく、組み込み型のfloatを使って欲しいので、こちらは削除してください。

2022-10-24 03:11 UTC, FumikaDemachi commented on neclib/devices/weather_status/tr73u.py
> +    def get_humid(self) -> float64:
```suggestion
    def get_humid(self) -> float:
```

2022-10-24 03:12 UTC, FumikaDemachi commented on neclib/devices/weather_status/weather_base.py
> +    def get_humid(self) -> float64:
```suggestion
    def get_humid(self) -> float:
```

2022-10-24 03:13 UTC, FumikaDemachi requested changes
コメントした箇所の修正をお願いします。

2022-10-24 11:10 UTC, FumikaDemachi approved these changes
LGTM !

2022-10-24 11:11 UTC, merged