#187 implement signal generatoe
necst-telescope/neclib pull request #200
Opened 2022-10-24 08:35 UTC by yamatomatsuzuki

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #187

2022-10-24 12:12 UTC, KaoruNishikawa requested changes
@yamatomatsuzuki 
コメントした箇所の修正をお願いします。

2022-10-24 12:12 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/signal_generator_base.py
> +        ...
`set_onoff` という名前の意味が分かりづらい気がするので、`start_output, stop_output` のように変えられないでしょうか？

また [ogameasure/device/Phasematrix/QuickSyn_FSW0000.py](https://github.com/ogawa-ros/ogameasure/blob/2259b96d61af9c25fcddc38c89f0b0f54a8c5c44/ogameasure/device/Phasematrix/QuickSyn_FSW0000.py#L194-L221) を使って `get_output_status` 関数を定義できますか？

2022-10-25 01:29 UTC, yamatomatsuzuki commented on neclib/devices/signal_generator/signal_generator_base.py
> +        ...
`set_onoff` を`start_output, stop_output`の二つに分割するということでしょうか。

2022-10-25 10:08 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/signal_generator_base.py
> +        ...
@yamatomatsuzuki 
その通りです。
ただ「変数名が分かりにくい」というのは制御の人間が持った感想なので @YuichiHori にも聞いてみてください。
関数名を `set_`、`get_` に統一していないのは freq, power といった "設定" と output の on/off は性質が違うように感じたためです。こちらについても確認しておいてほしいです。

2022-10-25 13:25 UTC, yamatomatsuzuki commented on neclib/devices/signal_generator/signal_generator_base.py
> +        ...
@KaoruNishikawa 
分かりました。ありがとうございます。

2022-10-26 09:42 UTC, KaoruNishikawa requested changes
@yamatomatsuzuki 
コメントした部分の修正をお願いします。

2022-10-26 09:42 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0010.py
> +            self.busy = True
`self.busy` が `True` の場合は「他の処理を実行中で新しい処理は受け付けられない」状態です。
そのためできれば busy でなくなるまで待機し、その後に通信 (`self.sg.freq_set`) を行うように変更してほしいです。

2022-10-26 09:42 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0020.py
> +        self.sg = ogameasure.Phasematrix.FSW0010(com)
```suggestion
        self.sg = ogameasure.Phasematrix.FSW0020(com)
```

2022-10-26 09:42 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/__init__.py
> +from .fsw0020 import fsw0020  # noqa: F401
クラス名の変更を反映してください。
```suggestion
from .fsw0010 import FSW0010  # noqa: F401
from .fsw0020 import FSW0020  # noqa: F401
```

2022-10-27 06:33 UTC, yamatomatsuzuki commented on neclib/devices/signal_generator/fsw0010.py
> +            self.busy = True
@KaoruNishikawa 
```suggestion
        while self.busy is True:
            time.sleep(1)
```
if文ではなくwhile文でこのように書いたらいいでしょうか。

2022-10-27 08:07 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0010.py
> +            self.busy = True
@yamatomatsuzuki 
良いと思います！

2022-10-28 02:35 UTC, KaoruNishikawa requested changes
@yamatomatsuzuki 
busy状態の条件判定を見直してみてください。

2022-10-28 02:35 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0010.py
> +            self.sg.freq_set(freq_GHz)
この通信を始める前に `self.busy = True` として、他の通信が割り込むのを防いでほしいです。

2022-10-28 02:35 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0010.py
> +            self.busy = True
通信が終わったら `self.busy = False` とし、他の関数を実行できるようにしてください。

2022-10-28 04:48 UTC, yamatomatsuzuki commented on neclib/devices/signal_generator/fsw0010.py
> +            self.busy = True
@KaoruNishikawa 
```
while self.busy is True:
    time.sleep(1)
else:
    self.busy = True
    self.sg.freq_set(freq_GHz)
    time.sleep(1)
    self.busy = False
    return
```
このようにすれば良いでしょうか

2022-10-28 04:59 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0010.py
> +            self.busy = True
@yamatomatsuzuki 
良いと思います！

2022-10-28 11:08 UTC, KaoruNishikawa reviewed
特に問題はないと思います。 @YuichiHori にも確認してもらうので少し待ってください。

2022-10-31 09:19 UTC, YuichiHori commented on neclib/devices/signal_generator/fsw0010.py
> +            return
この関数は現在の周波数を返す関数ですが、返り値が設定されていません。
このままこの関数を呼び出しても何も返ってこないので、周波数が返り値となるように修正してください。
他のgetと名のつく関数も同様にお願いします。

2022-11-09 06:03 UTC, YuichiHori approved these changes
良いと思います！

2022-11-09 06:05 UTC, KaoruNishikawa submitted a review, later dismissed
LGTM!

2022-11-09 08:29 UTC, YuichiHori requested changes
0020のflagが逆
configにデバイスの追加もよろしく

2022-11-09 09:55 UTC, KaoruNishikawa requested changes

2022-11-09 09:55 UTC, KaoruNishikawa commented on neclib/src/config.toml
> +dev_signal_generator = "FSW0010"
```suggestion
```

同じ種類 (モーター、SGのような区切り) のデバイスを複数使う方法は検討中なのでとりあえず FSW0020 だけ設定しておけばokです

2022-11-09 09:55 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/signal_generator_base.py
> +        ...
ここにも `finalize` を追加しておいてください

2022-11-09 09:55 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/signal_generator_base.py
> +    def get_output_status(self) -> int:
返り値が `bool` だとありがたいです

2022-11-09 09:55 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/fsw0020.py
> +            return
```suggestion
    def finalize(self):
        self.stop_output()
        try:
            self.sg.com.close()
        except AttributeError:
            pass
```

出力を止める処理は同じクラス内に定義した `stop_output` が再利用できるはずです。
通信を切断する処理はたまに失敗するので `try: 失敗するかもしれない処理 except: 失敗したときの処理` を使ってください。

2022-11-09 09:55 UTC, KaoruNishikawa commented on neclib/devices/signal_generator/signal_generator_base.py
> +
返り値が `astropy.units.Quantity` だとありがたいです

2022-11-09 10:12 UTC, yamatomatsuzuki commented on neclib/devices/signal_generator/signal_generator_base.py
> +    def get_output_status(self) -> int:
ogameasureから1が返ってきたら `True`, 0が返ってきたら`False`と出力するように書きかえたら良いのでしょうか.

2022-11-10 09:46 UTC, YuichiHori requested changes

2022-11-10 09:46 UTC, YuichiHori commented on neclib/devices/signal_generator/fsw0010.py
> +            return f * u.Hz
パワーの単位がHzになってるのでdBmに直してください。

2022-11-11 05:39 UTC, YuichiHori submitted a review, later dismissed
良いと思います！

2022-11-16 08:42 UTC, KaoruNishikawa approved these changes
LGTM!

2022-11-16 08:44 UTC, merged