#247 thermo
necst-telescope/neclib pull request #250
Opened 2022-11-11 08:52 UTC by TatsumiISHIKAWA

Adding class of Thermometer. Please check it.

2022-11-11 15:33 UTC, KaoruNishikawa requested changes
@TatsumiISHIKAWA 
コメントした箇所の修正をお願いします。

2022-11-11 15:33 UTC, KaoruNishikawa commented on neclib/devices/thermometer/l_218.py
> +    Model = "Model218"
混乱を避けるため、クラス名と `Model` の値を揃えてほしいです。
あと細かいですがメーカー名も正確に書いておきたいです。

```suggestion
class Model218(Thermometer):

    Manufacturer = "LakeShore"
    Model = "Model218"
```

2022-11-11 15:33 UTC, KaoruNishikawa commented on neclib/src/config.toml
> +rx_l218 = "Model218"
このパラメータは使っていないはずなので、(型番に関係ない) デバイス名を指定する `dev_<名前> = "Model218"` のような名前にしていいように思います。

2022-11-11 15:33 UTC, KaoruNishikawa commented on neclib/devices/thermometer/thermometer_base.py
> +from abc import ABC, abstractmethod  # noaq:F401
`noqa` がなくても警告は出ないように見えます。

2022-11-12 01:49 UTC, TatsumiISHIKAWA commented on neclib/devices/thermometer/l_218.py
> +    Model = "Model218"
これについてですがこのファイルの名前自体も変えておいたほうがいいでしょうか。
l218.pt -> model218.py

2022-11-12 08:31 UTC, KaoruNishikawa commented on neclib/devices/thermometer/l_218.py
> +    Model = "Model218"
確かにファイル名・パラメータ名も揃えたほうがいいと思います！

2022-11-16 08:23 UTC, KaoruNishikawa approved these changes
LGTM!

2022-11-16 08:23 UTC, merged