#262 cpz340816
necst-telescope/neclib pull request #270
Opened 2022-11-24 09:49 UTC by yamatomatsuzuki

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #262

2022-11-24 10:47 UTC, KaoruNishikawa requested changes
@yamatomatsuzuki 
コメントした箇所の確認をお願いします。

2022-11-24 10:47 UTC, KaoruNishikawa commented on neclib/devices/bias_setter/bias_setter_base.py
> +    def set_param(self, voltage_V: float, ch: int) -> None:
よりわかりやすい関数名にしてほしいです。

2022-11-24 10:47 UTC, KaoruNishikawa commented on neclib/devices/bias_setter/cpz340816.py
> +            self.param_buff[ch] = voltage_V
この部分ではデバイスとの通信を行わないので、`busy` を使う必要はないと思います。

2022-11-24 10:47 UTC, KaoruNishikawa commented on neclib/devices/bias_setter/cpz340816.py
> +            }
`param_buff` をクリアする必要があるのか、確認してほしいです。

2022-11-24 12:51 UTC, yamatomatsuzuki commented on neclib/devices/bias_setter/cpz340816.py
> +            }
@KaoruNishikawa 
`set_param()`で`ch`に1~16以外の数字を入れると`param_buff`に間違ったデータが入ってしまうのでそれをクリアする目的だったのですが、そのような必要はないでしょうか。(`output_voltage()`する度にクリアされてしまうのも不便ですかね...)

2022-11-24 14:31 UTC, yamatomatsuzuki commented on neclib/devices/bias_setter/cpz340816.py
> +            }
分かりました。ありがとうございます。

2022-12-01 06:21 UTC, KaoruNishikawa approved these changes
LGTM!

2022-12-01 06:21 UTC, merged