#494 atomsphere conversion
necst-telescope/neclib pull request #497
Opened 2023-10-17 18:48 UTC by r-yamada1998

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #494

2023-10-18 08:14 UTC, TakutoIto requested changes
Reverse sign of dAz, dEl.
Change name of parameter about weather.
There are few test patterns.

2023-10-18 08:14 UTC, TakutoIto commented on neclib/coordinates/pointing_error/omu1p85m.py
>          return -1 * dAz, -1 * dEl
No need to revers the sign of dAz,dEl

2023-10-18 08:14 UTC, TakutoIto commented on neclib/coordinates/pointing_error/pointing_error.py
>          return _az - dAz, _el - dEl
reverse the sign of dAz,dEl

2023-10-18 08:14 UTC, TakutoIto commented on neclib/coordinates/pointing_error/pointing_error.py
> +        wl: u.micron,
phpa -> pressure 
tc -> temperature
rh -> relative_humidity
wl -> obs_wl

2023-10-23 12:08 UTC, TakutoIto requested changes
In omu1p85m.py ,  az0, el0

2023-10-23 12:08 UTC, TakutoIto commented on neclib/coordinates/pointing_error/omu1p85m.py
> +
apply offset return az+dAz, el+dEl.
So, az0, el0 = self.apply_offset(az,el)

2023-10-23 16:21 UTC, r-yamada1998 commented on neclib/coordinates/pointing_error/omu1p85m.py
> +
oh, no

2023-10-23 16:21 UTC, r-yamada1998 commented on neclib/coordinates/pointing_error/omu1p85m.py
> +
My mistake lol

2023-10-24 10:33 UTC, takayama-27 requested changes
write the comment in  English

2023-10-24 10:33 UTC, takayama-27 commented on neclib/coordinates/pointing_error/pointing_error.py
> +            # Zは天体の視位置(天頂角)
change to English

2023-10-30 12:10 UTC, TakutoIto approved these changes

2023-10-31 09:17 UTC, takayama-27 approved these changes
LGTM！

2023-10-31 09:17 UTC, merged