[WIP] #521 add ml2437a.py
necst-telescope/neclib pull request #522
Opened 2024-04-02 12:14 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #521

2024-04-02 12:15 UTC, takayama-27 commented
まだ途中ですが

2024-04-02 14:27 UTC, TatsumiISHIKAWA reviewed
@takayama-27 
- 途中とのことですけど気になったことを並べておきます。

1. config.tomlに載せる設定値ですが、**GPIBのPortは`1234`ではない**です。これはGPIB-Ethernet通信機自体のLANコネクタのポート番号です。GPIBに要求されるポート番号はGPIB経由で装置と通信するために必要なポート番号で、これは**デバイス側で設定する値で、デフォルト値はマニュアルによれば13です。**（要確認。）
2. `Identifier`が必要です。今回は`host`でいいかと思います。
3. **出力の値の単位は`mW`ではなく`dBm`** です。本来Astropyには存在しませんがneclib特有の定義により使えることになっています。
一応デバイス側で`W`にもできますが、計測上`dBm`のほうが便利なのとデフォルト単位が`dBm`なので変更しておいてください。
本来は[`ogameasure`にあるinitialize`](https://github.com/ogawa-ros/ogameasure/blob/557abe305b4393f6c558baa601892da915d27a09/ogameasure/device/Anritsu/ml2437a.py#L8-L12)を使うべきですがまぁいいでしょう。
4. **関数`finalize`を追加して下さい。** 使用後、接続の必要がなくなった時に通信を`close`する必要があります。[例：温度計LakeShore Model218](https://github.com/necst-telescope/neclib/blob/a6a937e937940e566cf6d266a58d1d33ce51a6d3/neclib/devices/thermometer/model_218.py#L70-L71)
5. **`self.logger`は必要ないかもしれません。** このインスタンスは、デバイス制御の過程で何かしらのメッセージを表示する必要がある場合にのみ用意するもので、今回は不要かもしれません。

- Pull Request自体は実機での動作確認が終わり次第通します。

2024-04-02 14:46 UTC, takayama-27 commented
続きは明日ね

2024-04-03 08:52 UTC, takayama-27 commented
> 関数finalizeを追加して下さい。 使用後、接続の必要がなくなった時に通信をcloseする必要があります。[例：温度計LakeShore Model218](https://github.com/necst-telescope/neclib/blob/a6a937e937940e566cf6d266a58d1d33ce51a6d3/neclib/devices/thermometer/model_218.py#L70-L71)

https://github.com/ogawa-ros/ogameasure/blob/master/ogameasure/device/Anritsu/ml2437a.py
これを見ると、maの方はcloseって関数があるけどml2437aにはclose的な関数がないけどどれ使えばいいのかな？

2024-04-03 08:57 UTC, TatsumiISHIKAWA commented
@takayama-27 
> > 関数finalizeを追加して下さい。 使用後、接続の必要がなくなった時に通信をcloseする必要があります。[例：温度計LakeShore Model218](https://github.com/necst-telescope/neclib/blob/a6a937e937940e566cf6d266a58d1d33ce51a6d3/neclib/devices/thermometer/model_218.py#L70-L71)
> 
> https://github.com/ogawa-ros/ogameasure/blob/master/ogameasure/device/Anritsu/ml2437a.py これを見ると、maの方はcloseって関数があるけどml2437aにはclose的な関数がないけどどれ使えばいいのかな？

- `close`はPowerMeterのMethodではなくcommunicatorである`gpib_prologix`のmethodです。なので温度計でも`thermometer.close()`ではなく`thermometer.com.close`まで遡っています。

https://github.com/ogawa-ros/ogameasure/blob/557abe305b4393f6c558baa601892da915d27a09/ogameasure/communicator/gpib_prologix.py#L35-L38

2024-04-03 10:09 UTC, TatsumiISHIKAWA reviewed
@takayama-27 
シミュレータモードだけ念の為`true`に戻しておいてください。

2024-04-03 14:12 UTC, TatsumiISHIKAWA requested changes
ちょっとした部分ですが最後の変更お願いします。

2024-04-03 14:12 UTC, TatsumiISHIKAWA commented on neclib/devices/power_meter/ml2437a.py
> +        return
```suggestion
    def finalize(self): -> None
        self.pm.com.close()
        return
```

2024-04-04 04:08 UTC, takayama-27 commented
修正しました

2024-04-04 04:21 UTC, TatsumiISHIKAWA approved these changes
LGTM！お疲れ様でした

2024-04-04 04:21 UTC, merged