[WIP] #528 add LOattenuator
necst-telescope/neclib pull request #529
Opened 2024-04-08 17:47 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #528 

まだ全然途中です

2024-04-09 09:30 UTC, TatsumiISHIKAWA commented
@takayama-27 
- `Manufacturer`は`Interface`でいいです（これは各デバイスの製造会社名を入れるところです
- `Identifier`は`rsw_id`でいいです。
- `RIOH10`はdBで指定しますが`CPZ340516`をmAでしか指定できないので、`attenuator`ではなく`device_base`のレベルから別デバイスにしたほうが良い気がしないでもないです。
  - 例えば、新しく`da_converter(hogehoge)`みたいなものを作って、その中に新しく電流を出力するデバイスとして作ったほうがわかりやすい気がします。（これ自体はAttenuatorではないため。）
- ただし、necst/rxとの折り合いもあると思うのでそのあたりはしっかり設計を考える必要があるかもしれません。
  - 案として、「このデバイスは何かしらのda_converterとして実装し、config.tomlには`attenuator.1stLO`のように書き込み、necst/rxでも同様に扱い、既存の`RIOH10`のattenuator Nodeと別個管理する(`attenuator.IF`などに変更する) 」という手段があると思います...このあたりは試験と検討が必要です。

2024-04-10 07:33 UTC, takayama-27 commented
baseをどのようにするかは以前検討中。
とりあえず、細かいことは考えずに関数の中身を変更

2024-04-12 19:24 UTC, takayama-27 commented
これでもう完成にしてください

2024-04-13 18:05 UTC, takayama-27 commented
あと実機で動作確認したら終わり

2024-04-17 00:58 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +            except Exception as e:
@takayama-27 
結局今回のデバッグでこのエラーは解消できなかったですか？
これはこのままにしておいても制御できたと思って良いのでしょうか(Errorを表示はしますが`pass`になっているので必須でなければこの`try except`のエラー処理はない方がいいかと思いました)

2024-04-17 01:10 UTC, TatsumiISHIKAWA commented on neclib/defaults/config.toml
> +ch_num = 8
@takayama-27 
`CPZ340516`の中でこの引数を使っていないように見えます。必要でないなら削除してください。

2024-04-17 01:10 UTC, TatsumiISHIKAWA commented on neclib/defaults/config.toml
> +simulator = false
@takayama-27 
デバッグが完了次第最後にtrueに戻しておいてください

2024-04-17 02:43 UTC, takayama-27 commented on neclib/defaults/config.toml
> +ch_num = 8
necstで使ってるよ

2024-04-17 02:45 UTC, takayama-27 commented on neclib/defaults/config.toml
> +simulator = false
すみませんでした

2024-04-17 02:46 UTC, takayama-27 commented on neclib/devices/attenuator/cpz340516.py
> +            except Exception as e:
山田さんにも確認しましたが、残さないとこれ以外のerrorのキャッチができなくなっちゃうとのことなので残したい

2024-04-17 02:52 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +            except Exception as e:
了解です

2024-04-17 03:35 UTC, TatsumiISHIKAWA reviewed
@takayama-27 
1. 現状の実装だと、電流を指示する時にチャンネル番号を直接指示するようになっていますが、これだとユーザーフレンドリーでないです。
今回の実装ではとりあえず動くものができているので今後の実装項目（＝今回のPull Requestではとりあえず無視して新たにIssueを立てて対応する）にしてもいいですが、`SISBiasSetter`や`SISBiasReader`のように「人間が読めるチャンネル設定をconfig.tomlに書き込んでおいて、Code内でParseする」という実装のほうがnecstのCommanderを使うことを考慮しても適切です。
今回のPull Requestでこれに取り組むとまたParseできるかのデバッグなどが必要ですし、necst内の構文も若干変更する必要がありますが、どうしますか？

https://github.com/necst-telescope/neclib/blob/4e4695ca37f23a37e91ce5489996b5442b6e6be3/neclib/defaults/config.toml#L117

2. 上記の修正をした場合、`SISBiasSetter`などのように、各チャンネルに対する設定を書きやすくなります。観測中などに電流設定の範囲を変更することはまず無いと考えられるので（電圧計CPZ3177も同じ思想で実装しています）、`set_outputrange`は`__init__`内でconfigを読み取って実行してしまって問題ない気がします。
現状のように`set_outpurange`関数を保持したまま、この関数を`__init__`で実行すると実装としてはスッキリすると思います。
以下はCPZ3177に於ける、読み取り設定のまとめ指示Codeの例です。

https://github.com/necst-telescope/neclib/blob/4e4695ca37f23a37e91ce5489996b5442b6e6be3/neclib/defaults/config.toml#L115-L116

https://github.com/necst-telescope/neclib/blob/4e4695ca37f23a37e91ce5489996b5442b6e6be3/neclib/devices/ad_converter/cpz3177.py#L94-L97

2024-04-17 04:00 UTC, takayama-27 commented
たしかにその方がよさそう

2024-04-17 04:07 UTC, TatsumiISHIKAWA commented on neclib/defaults/config.toml
> +ch_num = 8
range = "DA0_100mA"

2024-04-17 04:08 UTC, TatsumiISHIKAWA commented on neclib/defaults/config.toml
> +ch_num = 8
```suggestion
ch_num = 8
range = "DA0_100mA"
```

2024-04-17 04:13 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +
```suggestion
        self.rsw_id = self.Config.rsw_id
        self.range = self.Config.range
        self.ch_num = self.Config.ch_num
        self.io = pyinterface.open(3405, self.rsw_id)
        for i in range(1, self.ch_num+1):
            self.io.set_outputrange(i, self.range)
       
```

2024-04-17 04:15 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +            return self.io.get_outputrange(ch)
```suggestion
    def get_outputrange(self, id: str) -> dict:
        with busy(self, "busy"):
            ch = self.Config.channel[id]
            return self.io.get_outputrange(ch)
```

2024-04-17 04:18 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +                    raise ValueError(f"Invalid channel: {ch}")
```suggestion
    def set_outputrange(self, id: str, outputrange: str) -> None:
        with busy(self, "busy"):
            ch = self.Config.channel[id]
            try:
                self.io.set_outputrange(ch, outputrange)
            except Exception as e:
                if e == "lspci: Unable to load libkmod resources: error -2":
                    pass
                else:
                    raise ValueError(f"Not found ID: {id}")
```

2024-04-17 04:18 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +            self.io.output_current(ch, current)
```suggestion
    def output_current(self, id: str, current: float):
        with busy(self, "busy"):
            ch = self.Config.channel[id]
            self.io.output_current(ch, current)
```

2024-04-17 04:21 UTC, TatsumiISHIKAWA requested changes
@takayama-27 
であれば次のように変更を提案します。
一度確認してみて良さそうなら反映して下さい。（necstへの反映もあると思いますので...）
もし実際に反映するのであれば一度試験することをおすすめしますが、必須ではないかなと思います。それから`config.toml`に項目が増えるので追記をしてください。

2024-04-17 04:31 UTC, r-yamada1998 commented on neclib/devices/attenuator/cpz340516.py
> +            except Exception as e:
@TatsumiISHIKAWA 
このバグは、unix packageの方のlspciのバージョンとFACの相性に由来するので、多分ここで修正するのは難しいです。

2024-04-17 04:32 UTC, r-yamada1998 commented on neclib/devices/attenuator/cpz340516.py
> +            except Exception as e:
ただ、エラーは出ても問題なく動くことが確認しています。

2024-04-17 04:38 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/cpz340516.py
> +            except Exception as e:
@r-yamada1998 
了解です。理解しました。
ではとりあえずこの部分はこれで良さそうですね。

2024-04-22 09:36 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/attenuator_base.py
> +        ...
- NetworkAttenuatorにはこれらの関数が存在しません。

2024-04-22 09:39 UTC, TatsumiISHIKAWA reviewed
@takayama-27 
一度チェックをお願いします。

一応necst経由で動作試験ができているので問題はないと思いますが、NetworkAttenuatorとCurrentAttenuatorがneclibを使用する環境上で共存、もしくは今回やっていないこの変更下でのNetworkAttenuator単体の試験を今後するべきです。野辺山に出張したときなどに計画するようにしましょう。

2024-04-22 10:03 UTC, takayama-27 commented on neclib/devices/attenuator/attenuator_base.py
> +        ...
get, set, outputは必要だって言われたからだと思うけど。
Networkは電流の値を制御するわけじゃないから一緒にはできなかったでしょ？

2024-04-22 10:11 UTC, TatsumiISHIKAWA commented on neclib/devices/attenuator/attenuator_base.py
> +        ...
すみません、私の目が節穴だったようです。
Resolve.

2024-04-22 10:15 UTC, TatsumiISHIKAWA approved these changes
LGTM!

2024-04-22 10:15 UTC, merged