#531 dome
necst-telescope/neclib pull request #564
Opened 2024-07-19 10:05 UTC by takayama-27

**Checks**

- [ ] Debugging completed
- [x] Please debug me

**Related Issue**

This PR closes #531

2024-07-19 10:05 UTC, takayama-27 commented
necstに合わせる必要あり
最低限の機能は実装したつもろい

2024-07-24 09:13 UTC, r-yamada1998 requested changes
One change requested

2024-07-24 09:13 UTC, r-yamada1998 commented on neclib/devices/encoder/cpz6204.py
> +    Notes
これはpyinterface系のdeviceなので、usbportのことをdocsに書いておく必要はないかな？
usb接続ではありません

2024-07-24 09:41 UTC, takayama-27 commented on neclib/devices/encoder/cpz6204.py
> +    Notes
ドキュメント書き直しました

2024-07-28 06:32 UTC, r-yamada1998 approved these changes
Looks Good To Me

2024-07-28 06:32 UTC, merged